config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get "/zodiac/:id", to: "zodiacs#show", as: :zodiac
  get "/users/:user_id/journals/new", to: "journals#new", as: :user_root

  # get "/users/:user_id/journals/new", to: "journals#new", as: :user_root
  # post "/users/:user_id/journals", to: "journals#create"
  # get "/predict/:id", to: "predicts#show", as: :user_root
  # post "/predicts", to: "predicts#create", as: :user_root
  devise_for :users

  # Create routes for users to their journals
  resources :users do
    resources :journals
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :predict
  belongs_to :user
end

app/models/predict.rb
class Predict < ApplicationRecord
  has_many :journals
  has_many :users, through: :journals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :zodiac
  has_many :journals
  has_many :predicts, through: :journals
  # validates :zodiac_id, presence: true
end

app/models/zodiac.rb
class Zodiac < ApplicationRecord
  belongs_to :user
  belongs_to :predict

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  require 'net/http'
  require 'uri'
  require 'json'

  def after_sign_in_path_for(resource)
    @my_pred = Predict.where("zodiac_id =? and created_at > ?", current_user.zodiac_id, Time.now.midnight).last
    user_root_path(resource) if current_user
  end

  def after_update_path_for(resource)
    @user=User.find(current_user.id)
    @user.journals=Journal.where(user_id: current_user.id).last
    params[user_id: @user.journals.user_id]
    "/users(@user.journals.user_id)journals/new" if current_user
  end

  # def after_sign_in_path_for(resource)
  #     @predict = Predict.where("zodiac_id =? and pred_date > ?", current_user.zodiac_id, Time.now.midnight).first
  #     user_root_path(@predict.id) if current_user
  #   end

  def do_daily_all_predicts
    #  Test in console using- ApplicationController.new.do_daily_all_predicts()
    @zodiacs=Zodiac.all
    @zodiacs.each do |z|
      url = "http://horoscope-api.herokuapp.com/horoscope/today/"
      url=url+z.sign
      uri = URI(url)
      response = Net::HTTP.get(uri) # => String
      @prediction=JSON.parse(response)
      # puts "DATE- #{@prediction["date"]}"
      # puts "ID- #{z.id}"
      # puts "HORO- #{@prediction["horoscope"]}"
      @predict = Predict.create(
        pred_date: "#{@prediction["date"]}",
        zodiac_id: z.id,
        prediction: "#{@prediction["horoscope"]}"
      )
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @zodiacs = Zodiac.all
  end
end

app/controllers/horo_apis_controller.rb
class HoroApisController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'

  def new
    puts params.inspect
    @zodiac_name=params[:id]

    # set url to read
    url = "http://horoscope-api.herokuapp.com/horoscope/today/"
    url=url+@zodiac_name

    # encode URI using the URI constant
    uri = URI(url)

    # tell Net::HTTP to POST the URI
    response = Net::HTTP.get(uri) # => String
    # response.basic_auth uid, apikey

    @prediction=JSON.parse(response)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

before_action :current_user
before_action :my_pred
after_action :my_pred


  def my_pred
    @my_pred = Predict.where("zodiac_id =? and created_at > ?", current_user.zodiac_id, Time.now.midnight).last
  end

  # def my_pred
  #   @my_pred = Predict.where("zodiac_id =? and pred_date > ?", current_user.zodiac_id, Time.now.midnight).first
  # end

  def index
    if current_user
      @journals = Journal.where(user_id: current_user.id)
      # Will need to do join query to capture date and prediction values from Predicts talbe since only have id's.
      @journals.reverse
    else
      flash[:alert] = "Session timed out"
      redirect_to "/"
    end
end

  def show
    if current_user
      @journal=Journal.where(user_id: current_user.id).last
    else
      flash[:alert] = "Session timed out"
      redirect_to "/"
    end
end

  def new
    @params=params.inspect
    if @params.user_id.nil?
      @user = User.find(params[:id])
        else
      @user = User.find(params[:user_id])
    end
    if current_user
      @predict = Predict.find(my_pred)
      @pred_date=@predict.pred_date.strftime("%m/%d/%Y")
    else
      flash[:alert] = "Session timed out"
      redirect_to "/"
    end
  end

  def create
    @user = User.find(params[:user_id])
    @journal=@user.journals.build(journal_params)
    if current_user
      if @journal.save
        redirect_to user_journals_path
      else
        flash[:alert] = "Save unsuccessful"
        render :new
      end
    else
      flash[:alert] = "Session expired"
      render root_path
    end
  end

  def update
  end

  def destroy
  end

  private

  def journal_params
    params.require(:journal).permit(:user_id, :predict_id, :comment)
  end

end

app/controllers/predicts_controller.rb
class PredictsController < ApplicationController

  before_action :current_user

  def show
    @journal=Journal.new
    if current_user
      @predict = Predict.find(params[:id])
      @pred_date=@predict.pred_date.strftime("%m/%d/%Y")
    else
      flash[:alert] = "Session timed out"
      redirect_to "/"
    end
  end

  def create
    @journal = Journal.new(journal_params)
    if current_user
      @journal.user_id=@current_user.id
      @journal.predict_id=@current_user.id

      if @journal.save
        flash[:notice] = "Saved"
        redirect_to user_journal_path(id: params[:zodiac_id])
      else
        flash[:alert] = "Save unsucessful"
        render "new"
      end
    else
      flash[:alert] = "Session timed out"
      render "/"
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def after_update_path_for(resource)
    @user=User.find(current_user.id)
    @user.journals=Journal.where(user_id: current_user.id).last
    params[user_id: @user.journals.user_id]
    "/users(@user.journals.user_id)journals/new" if current_user
  end

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :zodiac_id, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :zodiac_id, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :current_user
before_action :my_pred

  def my_pred
    if current_user
      @my_pred = Predict.where("zodiac_id =? and created_at > ?", current_user.zodiac_id, Time.now.midnight).last
    end
  end

  # def index
  #   redirect_to "/"
  # end
  #
  # def show
  #   @user=User.find(id: current_user.id)
  #   @user.journals=Journal.where(user_id: current_user.id).last
  #   redirect_to "/users(@user.journals.user_id)journals/new"
  # end

end

app/controllers/zodiacs_controller.rb
class ZodiacsController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'

  before_action :current_user
  after_action :pred_id_lookup

  def show
    puts params.inspect
    # @zodiac_name=Zodiac.find(params[:id])

    # set url to read
    url = "http://horoscope-api.herokuapp.com/horoscope/today/"
    url=url+params[:id]

    # encode URI using the URI constant
    uri = URI(url)

    # tell Net::HTTP to GET the URI
    response = Net::HTTP.get(uri) # => String

    @prediction=JSON.parse(response)

  end

  def pred_id_lookup
    @zodiacs=Zodiac.all
    # @zodiac.build_journal
    @zodiac=Zodiac.where(sign: params[:id]).first
    pred_id=Predict.where(pred_date: params[:date], zodiac_id: "#{@zodiac["id"]}").first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/predicts_helper.rb
module PredictsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<h1>Your Daily Prediction</h1>

<% @zodiacs.each do |z| %>
  <span id="<%= z.sign %>"><%= link_to("#{z[:sign]}", zodiac_path(id: z.sign)) %></span>
<%end%>

app/views/journals/_journal_form.html.erb

<%= form_for([@user, @user.journals.new]) do |form| %>
    <%= form.hidden_field :predict_id, value: "#{@my_pred["id"]}", readonly: "true"%>
    <%= form.text_field :comment %>
    <%= form.submit %>
<% end %>

app/views/journals/index.html.erb
<h1>Journal</h1>

<%= @journals.each do |j| %>
  <div>
    <input type="text" value="<%=j.comment%>">
  </div>
  <BR>
<% end %>

app/views/journals/new.html.erb
<% if current_user %>
  <%= form.hidden_field :user_id, value: "#{current_user.id}", readonly: "true"%>
<% end %>
<input type="text" value="<%=@pred_date%>">
<textarea col="50" row="100"><%=@my_pred["prediction"]%></textarea>

<%= render "/journals/journal_form" %>

app/views/journals/show.html.erb
<h1>Need to show</>

<%= @journals.each do |j| %>
  <div>
    <%= text_area :predict_id, value: "#{@pred_id}" %>
    <%= text_field :comment %>
  </div>
  <BR>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoroscopeSympatico</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <p class="navbar-text pull-right">
    <%= link_to "Home", root_path, :class => 'navbar-link'  %>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %> |
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    </nav>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/zodiacs/show.html.erb
<input type="text" value="<%=@prediction["date"]%>">
<textarea col="50" row="100"><%=@prediction["horoscope"]%></textarea>
<input type="text" value="<%=@prediction["sunsign"]%>">
<label for="comment">Comment</label>
<input id="comment_sign_up" type="text" name="comment" value="">

<!-- Using Boostrap Modal styling but calling custom javascript code -->
<div id="signUpModal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="noThx close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">User Not Registered</h4>
      </div>
      <div class="modal-body">
        <p>You must sign up to save comments.</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign Up!", "/users/sign_up", id: "subButton", class: "btn btn-primary" %>
        <button type="button" class="noThx btn btn-default">No Thanks</button>
      </div>
    </div>
  </div>
</div>

<% if current_user.nil? %>
  <%= link_to "Save", "#", id: "comment_saveBtn", action: "sign_up_modal" %>
<% end %>